config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "searchs#index"

  resources :subjects, only: [:create]
  resources :resources, only: [:index, :show, :new, :create] do
    resources :sections, only: [:create, :destroy]
  end

  resources :articles, only: [:index, :new,  :create]

  resources :articles, only: [:show] do
    resources :translations, controller: 'articles/translations', only: [:new, :create, :edit, :update]
  end

  resources :sections, only: [:show] do
    resources :translations, only: [:new, :create, :show, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :similar_articles,
                          class_name: "Article",
                          join_table: "article_relations",
                          association_foreign_key: :article_relation_id

  has_one :translation, as: :translatable

  def related_articles
    ArticleRelation.all_related_articles(id)
  end
end

app/models/article_relation.rb
class ArticleRelation < ApplicationRecord
  def self.all_related_articles(id)
    article_ids = where(article_id: id).map(&:article_relation_id)
    article_relation_ids = where(article_relation_id: id).map(&:article_id)
    Article.find(article_ids + article_relation_ids)
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_and_belongs_to_many :similar_resources,
                          class_name: "Resource",
                          join_table: "resource_relations",
                          association_foreign_key: :resource_relation_id

  has_many :sections

  def related_resources
    ResourceRelation.all_related_resources(id)
  end
end

app/models/resource_relation.rb
class ResourceRelation < ApplicationRecord
  def self.all_related_resources(id)
    resource_ids = where(resource_id: id).map(&:resource_relation_id)
    resource_relation_ids = where(resource_relation_id: id).map(&:resource_id)
    Resource.find(resource_ids + resource_relation_ids)
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :resource
  has_many :translations, as: :translatable
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :resources

  def available_languages
    resources.map(&:language)
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :translatable, polymorphic: true
  has_rich_text :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles/translations_controller.rb
class Articles::TranslationsController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @translation = @article.build_translation
  end

  def create
    article = Article.find(params[:article_id])
    article.create_translation!(translation_params)
    # FIXME: redirect path
    # redirect_to section_translation_path(section_id: section.id, id: translation.id)
    redirect_to article_path(article)
  end

  def edit
    @article = Article.find(params[:id])
    @translation = @article.translation
  end

  def update
    translation = Translation.find(params[:id])
    translation.update!(translation_params)
    article = translation.translatable
    # FIXME: redirect path
    redirect_to article_path(article)
  end

  private

  def translation_params
    params.require(:translation).permit(:content)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(Article.arel_table[:name].matches("%#{params[:search_term]}%"))
  end

  def show
    @article = Article.find(params[:id])
    @related_articles = @article.related_articles
    @translation = @article.translation
  end

  def new
    @article = Article.new
    @root_article_id = params[:root_article_id]
  end

  def create
    if params[:root_article_id].present?
      article = Article.find(params[:root_article_id])
      related_articles = article.related_articles
      # TODO: this whole thing is blagh
      created_article = article.similar_articles.create!(article_params)
      related_articles.each do |related_article|
        ArticleRelation.create!(article_id: related_article.id, article_relation_id: created_article.id)
      end
      redirect_to article_path(created_article)
    else
      article = Article.new(article_params)
      if article.save!
        redirect_to article_path(article)
      else
        render status: 500
      end
    end
  end

  def article_params
    params.require(:article).permit(:name, :url, :language)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.where(Resource.arel_table[:name].matches("%#{params[:search_term]}%"))
  end

  def show
    @resource = Resource.find(params[:id])
    @sections = @resource.sections
    @related_resources = @resource.related_resources
  end

  def new
    # TODO: make this a post action so that the root cannot be changed
    @root_resource_id = params[:root_resource_id]
    @resource = Resource.new
  end

  def create
    # TODO: break out similar resource into it's own controller
    if params[:root_resource_id].present?
      resource = Resource.find(params[:root_resource_id])
      related_resources = resource.related_resources
      # TODO: add check for if saving actually works, break out into service?
      created_resource = resource.similar_resources.create!(resource_params)
      related_resources.each do |related_resource|
        ResourceRelation.create!(resource_id: related_resource.id, resource_relation_id: created_resource.id)
      end
      redirect_to resource_path(created_resource)
    else
      resource = Resource.new(resource_params)
      if resource.save!
        redirect_to resource_path(resource)
      else
        render status: 500
      end
    end
  end

  private

  def resource_params
    params.require(:resource).permit(:url, :language, :name)
  end

  # TODO: might be used??
  def similar_resource_params
    params.require(:resource).permit(:url, :language, :name).merge(resource_relation_id: params[:root_resource_id])
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index; end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.where(Section.arel_table[:title].matches("%#{params[:search_term]}%")).eager_load(:resources)
  end

  def show
    @section = Section.find(params[:id])
  end

  def create
    section = Section.new(section_params)
    if section.save!
      render json: {
        status: "Success",
        section_title: section.title,
        section_url: section.url,
        section_id: section.id,
      }
    end
  end

  def destroy
    section = Section.find(params[:id])
    section.translations.destroy_all
    section.destroy!
  end

  private

  def section_params
    params.require(:sections).permit(:resource_id, :url, :title)
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def new
    @section = Section.find(params[:section_id])
    @translation = @section.translations.new
  end

  def create
    section = Section.find(params[:section_id])
    translation = section.translations.create!(translation_params)
    redirect_to section_translation_path(section_id: section.id, id: translation.id)
  end

  def show
    @translation = Translation.find(params[:id])
  end

  def edit
    @translation = Translation.find(params[:id])
    @section = @translation.translatable
  end

  def update
    translation = Translation.find(params[:id])
    translation.update!(translation_params)
    redirect_to section_translation_path(section_id: translation.translatable.id, id: translation.id)
  end

  private

  def translation_params
    params.require(:translation).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_alternates.erb
<h5>Alternate Versions</h5>
<% unless related_articles.nil? %>
  <% related_articles.each do |article| %>
    <%= link_to article.language, article_path(article) %>
    <br />
  <% end %>
<% end %>

<%= link_to "Add", new_article_path(root_article_id: article) %>

app/views/articles/_search_results.html.erb
<div class="container search-result-item__container">
  <div class="search-result-item">
    <%= link_to article.name, article_path(article) %>
    <div class="search-result-item__content">
      <div class="search-result-item__snapshot"></div>
      <div class="search-result-item__details">
        <div>Languages: <%= article.language %></div>
        <div><%= article.url %></div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% if @articles.empty? %>
  <div>No Articles Found...</div>
  <%= link_to "Add Article", new_article_path %>
<% else %>
  <% @articles.each do |article| %>
    <%= render "search_results", article: article %>
  <% end %>
<% end %>
<%= javascript_pack_tag 'articles/index' %>

app/views/articles/new.html.erb
<div class="container">
  <%= form_for(@article, url: { action: "create" }) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :language %>
    <%= f.text_field :language %>
    <% if @root_article_id %>
      <%= hidden_field_tag :root_article_id, @root_article_id %>
    <% end %>
    <%= f.submit "Add Article" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<%# Article Header Area %>
<%= @article.name %>
<br />
<%= link_to @article.url, @article.url %>
<br />
<%= @article.language %>
<br />

<%= render "alternates", article: @article, related_articles: @related_articles %>

<br />

<% unless @translation.nil? %>
  <h1>Translation</h1>

  <div>
    <%= @translation.content %>
  </div>
<% end %>

<br />
<% unless @translation %>
  <%= link_to "Add Translations", new_article_translation_path(@article) %>
<% else %>
  <%= link_to "Edit Translations", edit_article_translation_path(@article) %>
<% end %>

app/views/articles/translations/edit.html.erb
<%= stylesheet_link_tag 'actiontext' %>
<%= javascript_pack_tag 'translations/new' %>
<%# TODO: use the real ID when implementing the edit and update actions %>
<%# are you just not suppose to nest update routes??? %>
<%= form_for @translation, method: :PUT, url: article_translations_path(article_id: @article.id) + "/#{@translation.id}" do |f| %>
  <div class="field">
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/articles/translations/new.html.erb
<%= stylesheet_link_tag 'actiontext' %>
<%= javascript_pack_tag 'translations/new' %>
<h1><%= @article.name %></h1>
<%= form_for @translation, url: article_translations_path do |f| %>
  <div class="field">
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kotodama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/resources/_alternates.html.erb
<div class="">
  <h5 class="">Alternate versions available in</h5>
  <div class="alt-lang-container">
    <ul>
      <% related_resources.each do |resource| %>
        <li class="alt-lang-item"><%= link_to resource.language, resource_path(resource) %></li>
      <% end %>
    </ul>
  </div>
  <%= link_to new_resource_path(root_resource_id: resource) do %>
    <div class="alt-lang-add-button">Add</div>
  <% end %>
</div>

app/views/resources/_no_results.html.erb
<div class="container">
  <h2>No Docs Found....</h2>
  <%= link_to "Create Resource", new_resource_path(search_term: params[:search_term]), class: "search-result-item__create-button" %>
</div>

app/views/resources/_search_results.erb
<div class="container search-result-item__container">
  <div class="search-result-item">
    <%= link_to resource.name, resource_path(resource) %>
    <div class="search-result-item__content">
      <div class="search-result-item__snapshot"></div>
      <div class="search-result-item__details">
        <div>Languages: <%= resource.language %></div>
        <div><%= resource.url %></div>
      </div>
    </div>
  </div>
</div>

app/views/resources/_sections.html.erb
<div class="">
  <h5 class="section-title">Sections</h5>
  <div class="section-container" id="section-container">
    <% if sections.present? %>
      <% sections.each do |section| %>
        <div class="section-item">
          <i class="material-icons section-icon__transformation">arrow_drop_down_circle</i>
          <div><%= link_to section.title, section.url %></div>
          <i class="material-icons section-icon__transformation section-delete-button" data-delete-url="<%= resource_section_path(resource_id: section.resource.id, id: section.id) %>">clear</i>
          <% if section.translations.exists? %>
            <%= link_to section_translation_path(section_id: section.id, id: section.translations.first.id) do %>
              <i class="material-icons">book</i>
            <% end %>
          <% else %>
            <%= link_to new_section_translation_path(section_id: section.id) do %>
              <i class="material-icons">bookmark</i>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="hidden-inputs" id="section-field-inputs">
    <label for="url">URL</label>
    <input type="text" name="url"/>
    <label for="title">title</label>
    <input type="text" name="title"/>
  </div>
  <button class="section-add-button" id="section-add-button"  data-resource-id="<%= @resource.id %>">Add Section</button>
</div>

app/views/resources/_snapshot_detail.erb
<div class="subject-site__information">
  <div class="subject-site__snapshot"></div>
  <div class="subject-site__detail">
    <div>URL: <%= resource.url %></div>
    <div>Language: <%= resource.language %></div>
  </div>
</div>

app/views/resources/index.html.erb
<main class="search-result__main-content">
  <% if @resources.empty? %>
    <%= render "no_results" %>
  <% else %>
    <div class="container search-result-area">
      <div>Search Result for <p class="search-term"><%= params[:search_term] %></p></div>
      <% @resources.each do |resource| %>
        <%= render "search_results", resource: resource %>
      <% end %>
    </div>
  <% end %>
  <%= javascript_pack_tag 'resources/index' %>
</main>

app/views/resources/new.html.erb
<div class="container">
  <%= form_for(@resource, url: { action: "create" }) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :language %>
    <%= f.text_field :language %>
    <% if @root_resource_id %>
      <%= hidden_field_tag :root_resource_id, @root_resource_id %>
    <% end %>
    <%= f.submit "Create Resource" %>
  <% end %>
</div>

app/views/resources/show.html.erb
<div class="container">
  <h3 class="title"><%= @resource.name %></h3>
</div>
<div class="row">
  <div class="col s3 offset-s1">
    <%= render "snapshot_detail", resource: @resource %>
  </div>
  <div class="col s4">
    <%= render "sections", sections: @sections %>
  </div>
  <div class="col s3">
    <%= render "alternates", resource: @resource, related_resources: @related_resources %>
  </div>
</div>
<%= javascript_pack_tag 'resources/show' %>

app/views/searchs/index.html.erb
<div class="container search">
  <% # TODO: use form tag helper %>
  <div class="row">
    <div class="col s8 offset-s2">
      <form id="search_action">
        <div class="input-field">
          <input class="search-bar" type="text" name="search_term" />
        </div>
      </form>
      <select id="select_box">
        <option value="articles" id="select_article">Article</option>
        <option value="resources" id="select_documentation">Documentation</option>
      </select>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'searchs/index' %>

app/views/sections/show.html.erb
<h1><%= @section.title %></h1>

app/views/shared/_header.html.erb
<nav class="navigation-bar">
  <div class="nav-wrapper green lighten-3">
    <div class="row">
      <div class="col s12">
        <a class="brand-logo" href="/">
          Kotodama Documentation Search
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <!-- <li>Sign In</li> -->
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/subjects/_search_results.erb
<div class="container search-result-item__container">
  <div class="search-result-item">
    <%= link_to subject.name, subject_path(subject) %>
    <div class="search-result-item__content">
      <div class="search-result-item__snapshot"></div>
      <div class="search-result-item__details">
        <div>Languages: EN, JP, CH</div>
        <div>www.github.com</div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/_sections.html.erb
<div class="">
  <h5 class="section-title">Sections</h5>
  <div class="section-container" id="section-container">
    <% if sections.present? %>
      <% sections.each do |section| %>
        <div class="section-item">
          <i class="material-icons section-icon__transformation">arrow_drop_down_circle</i>
          <div><%= section.title %></div>
          <i class="material-icons section-icon__transformation section-delete-button" data-delete-url="<%= section_path(section) %>">clear</i>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="hidden-inputs" id="section-field-inputs">
    <label for="url">URL</label>
    <input type="text" name="url"/>
    <label for="title">title</label>
    <input type="text" name="title"/>
  </div>
  <button class="section-add-button" id="section-add-button">Add Section</button>
</div>

app/views/subjects/_snapshot_detail.erb
<div class="subject-site__information">
  <div class="subject-site__snapshot"></div>
  <div class="subject-site__detail">
    <div>URL: www.github.com</div>
    <div>Language: EN</div>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="container">
  <%= form_for(@subject, url: { action: "create" }) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :language %>
    <%= f.text_field :language %>
    <%= f.submit "Create Subject" %>
  <% end %>
</div>

app/views/translations/edit.html.erb
<%= stylesheet_link_tag 'actiontext' %>
<%= javascript_pack_tag 'translations/new' %>
<%# TODO: use the real ID when implementing the edit and update actions %>
<%# are you just not suppose to nest update routes??? %>
<%= form_for @translation, method: :PUT, url: section_translations_path(section_id: @section.id) + "/#{@translation.id}" do |f| %>
  <div class="field">
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/translations/new.html.erb
<%= stylesheet_link_tag 'actiontext' %>
<%= javascript_pack_tag 'translations/new' %>
<h1><%= @section.title %></h1>
<%= form_for @translation, url: section_translations_path do |f| %>
  <div class="field">
    <%= f.rich_text_area :content %>
  </div>
  <%= f.submit %>
<% end %>

app/views/translations/show.html.erb
<div>
  <%= @translation.content %>
</div>

<%= link_to "Edit", edit_section_translation_path(section_id: @translation.translatable.id, id: @translation.id) %>
<br />
<%= link_to "Back to Section", resource_path(@translation.translatable.resource) %>